name: DevSecOps Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
      - name: Run Unit Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest -q

  sonarcloud:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: SonarCloud Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        timeout-minutes: 5

  trivy_sca:
    runs-on: ubuntu-latest
    needs: sonarcloud
    steps:
      - uses: actions/checkout@v2
      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "table"
          exit-code: "1" # Fail the pipeline if vulnerabilities found
          severity: "CRITICAL,HIGH"
      - name: Generate JSON report
        run: |
          trivy fs --severity CRITICAL,HIGH --format json . > trivy-report.json
      - name: Generate SBOM (CycloneDX)
        run: |
          trivy fs --format cyclonedx --output sbom.cdx .
      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v5
        with:
          name: trivy-reports
          path: |
            trivy-report.json
            sbom.cdx

  zap_scan:
    runs-on: ubuntu-latest
    needs: trivy_sca
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t vulnerable-app .
      - name: Run container
        run: docker run -d --name app --network=host -p 8000:8000 vulnerable-app
      - name: Wait for application to be ready
        run: |
          timeout 30s bash -c 'until curl -s http://127.0.0.1:8000/vulnerable > /dev/null; do echo "Waiting for app to start..."; sleep 2; done' || exit 1
          echo "Application is ready!"
      - name: Check app from runner
        run: |
          curl -v http://127.0.0.1:8000/vulnerable || echo "App not reachable"
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: http://127.0.0.1:8000/vulnerable
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-a"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Stop Docker container
        if: always()
        run: |
          docker stop app
          docker rm app

